(
  &tcpc "adventofcode.com:443"
  +@\0↙128↘-128⊢⇌⊚⌕-@\0".adventofcode.com".&frab "C:\\Users\\azure\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\yd8d9ixf.default-release\\cookies.sqlite"
  &httpsw ⊂ "GET /2015/day/5/input HTTP/1.0\nCookie: session="
  ↘+4⊗"\r\n\r\n"◫4.
  &fwa ,
  &fras
|&fras) &fe. "day5.txt"
Forbidden ← ["ab" "cd" "pq" "xy"]
↯¯1_16▽≠@\n.
▽≡(/↥≡/=◫2⊛).
▽≥3≡(/+∊ "aeiou").
▽¬≡/↥/↥⊠⌕ Forbidden.
⧻.
