# Experimental!
$ 00100
$ 11110
$ 10110
$ 10111
$ 10101
$ 01111
$ 00111
$ 11100
$ 10000
$ 11001
$ 00010
$ 01010
∵⋕↯⊂∞⊃(⧻°□⊢⊜□⊸≠@\n|▽⊸≠@\n)
# Keep numbers starting with 1
# ▽=1⊸⍜⍉(⊡0)
# Keep rows which have X in column M

# SelectedNumbers ? X M Numbers
SelectNumber ← ▽=⊸⊙⍜⊙⍉⊡

# BitFrequencies ? M Numbers
BitFreq    ← ⍜⍉≡/+=
MostCommon ← ⊡⁅÷2⊸⧻⊏⊸⍏

# Oxygen Generator Rating
⊸⍜⍉(≡MostCommon)
⊙(⍜⍉⊸⧻)
⊙⊙¤
≡SelectNumber
